# Generated by Django 4.1.2 on 2022-10-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Device_Name', models.CharField(max_length=255, verbose_name='Device Name')),
                ('Product_Price', models.CharField(max_length=255, verbose_name='product price')),
                ('Product_Type', models.CharField(max_length=255, verbose_name='product type')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RUDevice',
            fields=[
                ('Id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('product_price', models.CharField(max_length=255, verbose_name='product price')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RemoteUnit.producttype')),
            ],
        ),
    ]
